// 鉄道事業者・路線名の英語表記。
// 駅データ（OpenStreetMap 由来）は日本語表記のみを持つため、英語 UI 用の
// 対訳をここで持つ。表記は各社の公式英語名（駅ナンバリング用の英字表記）に合わせ、
// 長音記号は付けない（Tōkyō ではなく Tokyo）。旅行者が駅の案内表示と
// 照合できることを最優先している。

/** 事業者名 → 英語表記。 */
export const OPERATOR_EN: Record<string, string> = {
  JR東日本: 'JR East',
  JR東海: 'JR Central',
  つくばエクスプレス: 'Tsukuba Express',
  ゆりかもめ: 'Yurikamome',
  りんかい線: 'Rinkai Line',
  京急電鉄: 'Keikyu',
  京成電鉄: 'Keisei',
  京王電鉄: 'Keio',
  北総鉄道: 'Hokuso Railway',
  多摩都市モノレール: 'Tama Monorail',
  小田急電鉄: 'Odakyu',
  東京メトロ: 'Tokyo Metro',
  東京モノレール: 'Tokyo Monorail',
  東急電鉄: 'Tokyu',
  東武鉄道: 'Tobu',
  西武鉄道: 'Seibu',
  都営地下鉄: 'Toei Subway',
};

/** 路線名 → 英語表記。 */
export const LINE_EN: Record<string, string> = {
  つくばエクスプレス: 'Tsukuba Express',
  ゆりかもめ: 'Yurikamome',
  りんかい線: 'Rinkai Line',
  上野東京ライン: 'Ueno-Tokyo Line',
  '中央・総武線各停': 'Chuo-Sobu Line (Local)',
  中央線快速: 'Chuo Line (Rapid)',
  丸ノ内線: 'Marunouchi Line',
  京急本線: 'Keikyu Main Line',
  京成本線: 'Keisei Main Line',
  京浜東北線: 'Keihin-Tohoku Line',
  京王井の頭線: 'Keio Inokashira Line',
  京王線: 'Keio Line',
  京葉線: 'Keiyo Line',
  副都心線: 'Fukutoshin Line',
  千代田線: 'Chiyoda Line',
  半蔵門線: 'Hanzomon Line',
  南北線: 'Namboku Line',
  南武線: 'Nambu Line',
  埼京線: 'Saikyo Line',
  多摩都市モノレール: 'Tama Monorail',
  小田急多摩線: 'Odakyu Tama Line',
  小田急小田原線: 'Odakyu Odawara Line',
  山手線: 'Yamanote Line',
  常磐線各停: 'Joban Line (Local)',
  常磐線快速: 'Joban Line (Rapid)',
  日比谷線: 'Hibiya Line',
  有楽町線: 'Yurakucho Line',
  東急世田谷線: 'Tokyu Setagaya Line',
  東急多摩川線: 'Tokyu Tamagawa Line',
  東急大井町線: 'Tokyu Oimachi Line',
  東急東横線: 'Tokyu Toyoko Line',
  東急池上線: 'Tokyu Ikegami Line',
  東急田園都市線: 'Tokyu Den-en-toshi Line',
  東急目黒線: 'Tokyu Meguro Line',
  東武スカイツリーライン: 'Tobu Skytree Line',
  東武東上線: 'Tobu Tojo Line',
  東西線: 'Tozai Line',
  横浜線: 'Yokohama Line',
  武蔵野線: 'Musashino Line',
  湘南新宿ライン: 'Shonan-Shinjuku Line',
  西武新宿線: 'Seibu Shinjuku Line',
  西武池袋線: 'Seibu Ikebukuro Line',
  都営三田線: 'Toei Mita Line',
  都営大江戸線: 'Toei Oedo Line',
  都営新宿線: 'Toei Shinjuku Line',
  都営浅草線: 'Toei Asakusa Line',
  銀座線: 'Ginza Line',
};
